site_name: Alexandra Palacio Morales
theme:
  name: material
  logo: assets/images/logo.png
palette:
  scheme: slate  # or 'default' for light
font:
  text: Roboto
  code: Roboto Mono
features:
  - navigation.instant
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - header.autohide
  - search.highlight
  - search.suggest
  - content.code.copy
  - content.action.edit
nav:
  - Home: index.md
  - Research: research.md
  - Open Positions: positions.md
  - Teaching: teaching.md
  - Lecture Notes & Documents: lecturenote.md
  - Publications: publications.md
  - Contact: contact.md
plugins:
  - macros
  - glightbox
  - encryptcontent:
      password_inventory:
        secret: "password1"   # define a level
extra_javascript:
  - js/swiper-bundle.min.js

extra_css:
  - css/swiper-bundle.min.css
  - styles/bio.css
  - css/neoteroi-mkdocs.css
  - css/gantt-overrides.css  # <-- must be after, so it wins	
markdown_extensions:
  - md_in_html        # <- allow Markdown inside HTML
  - neoteroi.timeline
  - attr_list
  - neoteroi.projects
extra:
  publist_path: assets/publications/publist.yml